m=matfile('spectra_corr.mat');
load('ygrid.mat')
load('mean_profiles.mat')
j=180;
uu=uu+Um.^2;
B=uu(j)*vv(j)-uv(j)^2;
L11=(vv(j)*m.Ruu(:,:,j)-uv(j)*m.Ruv(:,:,j))./B;
L12=(uu(j)*m.Ruv(:,:,j)-uv(j)*m.Ruu(:,:,j))./B;
L21=(vv(j)*m.Ruv(:,:,j)-uv(j)*m.Rvv(:,:,j))./B;
L22=(uu(j)*m.Rvv(:,:,j)-uv(j)*m.Ruv(:,:,j))./B;
u1=sqrt(uu(j))+Um(j);
u2=-sqrt(vv(j));
up1=u1*L11+u2*L12-Um(j);
up2=u1*L21+u2*L22;
